version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - TRANSMISSION_HOST=${PROD_TRANSMISSION_HOST}
      - TRANSMISSION_PORT=${PROD_TRANSMISSION_PORT}
      - TRANSMISSION_USERNAME=${PROD_TRANSMISSION_USERNAME}
      - TRANSMISSION_PASSWORD=${PROD_TRANSMISSION_PASSWORD}
    ports:
      - "${PROD_APP_PORT}:${PROD_APP_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    name: torrent-network
    driver: bridge